language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18-shrplib"
  - "5.20"
  - "5.20-shrplib"
  - "5.22"
  - "5.22-shrplib"
before_install:
  - find /home/travis/perl5/perlbrew/perls | grep MoreUtils
  - cpanm --installdeps .
  - find /home/travis/perl5/perlbrew/perls | grep MoreUtils
